version: '3.7'

services:

  frontend:
    container_name: ngcompleteguide
    build: 
      context: .
      dockerfile : ./Dockerfile
  nginx:
    container_name: nginxserver
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
    - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw